animalshare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), #в аргументе (в скобках),мы указываем где искать наш шаблон, в этом примере папка users, файл login
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
   
    path('', include('blog.urls'), name='blog-home'),
    path('messages/', include('usertouser.urls', namespace='usertouser')), #тут мы реализовали пространство имен, что б не было конфликтов с хтмл файлами назанными одинаково, при указании ссылок надо добавлять префикс указанный в пространстве имен, см фалйы хтмл в usertouser
    path('shop/', include('goods.urls'), name='shop'),
    path('cart/', include('carts.urls'), name='cart'),
    path('orders/', include('orders.urls'), name='orders'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from .views import PostDetailView, PostCreateView, PostListView, PostUpdateView, PostDeleteView, UserPostListView, AddCommentView, UserCommentListView, GalleryListView, Delete_Comment, About
from . import views


urlpatterns = [
    path('forum/', PostListView.as_view(), name='forum'),#blog-home
    re_path(r'^user/(?P<username>\w{0,50})/$', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comments', AddCommentView.as_view(), name='add_comment'),
    path('post/user_comments', UserCommentListView.as_view(), name='user-comments'),
    path('comment/delete/<int:comment_id>/', Delete_Comment, name='delete-comment'),
    path('post/gallery', GalleryListView.as_view(), name='gallery'),
    path('', About.as_view(), name='home'),#blog-about
] 

usertouser/urls.py
from django.urls import path
from .views import usertouserCreateView, usertouserListView, usertouserDetailListView, usertouserOutboxListView
app_name = 'usertouser' #указание для пространства имен в главном файле url.py


urlpatterns = [
path('sms/inbox/', usertouserListView.as_view(template_name='messages/inbox.html'), name='inbox'),
path('sms/create/<str:recipient>/', usertouserCreateView.as_view(), name='create_message'),
path('sms/outbox/', usertouserOutboxListView.as_view(template_name='messages/outbox.html'), name='outbox'),
path('sms/<int:pk>/', usertouserDetailListView.as_view(), name='detail'), 
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    animaltype = models.CharField(max_length=50)
    animalstatus = models.CharField(max_length=50, null=True)
    description = models.TextField()
    animal_image = models.ImageField(default='default_animal.jpg', upload_to='animal_pics')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
   

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk}) #перенаправление после создания поста в детали поста
    
    def __str__(self) -> str:
        return self.title
    

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'Author {self.comment_author}| post title {self.post.title}'
    #   return '%s - %s' % (self.post.title, self.comment_author)
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.post.pk})

blog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Post, Comment
from goods.models import Products
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from random import randint



class PostListView(ListView):
    model = Post
    template_name = 'home.html' #<app>/<model>_<view_type>.html это шаблон по которому джанго будет отрисовывать наши посты
    context_object_name = 'posts' #показываем название что зацикливать
    ordering = ['-date_posted'] #даем запрос в БД на отображение постов в порядке добавления
    paginate_by = 5 # метод, который позволяет оставить 5 постов на одну страницу

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получаю контекст из родительского класса
        context['comments'] = Comment.objects.all().order_by('-date_added')
        context['posts_quantity'] = Post.objects.count()
        context['users_quantity'] = User.objects.filter(is_active=True).count()
        context['products_quantity'] = Products.objects.count()
        context['title'] = 'Forum'
        context['variable'] = randint(1, 9)
        return context


class UserPostListView(ListView): #создание класса который отфильтрует посты пользователя
    model = Post
    template_name = 'user_posts.html' 
    context_object_name = 'posts'
    paginate_by = 5
    ordering = ['-date_posted']

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class GalleryListView(ListView): #создание класса который отфильтрует из БД все картинки
    model = Post
    template_name = 'gallery.html' 
    context_object_name = 'gallery'
    paginate_by = 18
    ordering = ['?']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получаю контекст из родительского класса
        context['gallery'] = Post.objects.exclude(animal_image='default_animal.jpg')#реализовано условие выборки из БД, КРОМЕ (что б не отображались стандартные пикчи животных)
        context['variable'] = randint(1, 9)
        context['title'] = 'Gallery'
        return context
    

class UserCommentListView(ListView): #создание класса который отфильтрует комментарии пользователя
    model = Comment
    template_name = 'user_comments.html' 
    context_object_name = 'comments'
    paginate_by = 20
    ordering = ['-date_added']

    def get_queryset(self):
        user = get_object_or_404(User, id=self.request.user.id)
        return Comment.objects.filter(comment_author=user).select_related('comment_author')

@login_required
def Delete_Comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, comment_author=request.user)
    if request.method == 'POST':
        comment.delete()
        return redirect('user-comments')  # Перенаправление на страницу с комментариями
    return render(request, 'confirm_delete.html', {'comment': comment}, {'title': 'Your comments'},)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'animaltype', 'animalstatus', 'description', 'animal_image']

    def form_valid(self, form):
        form.instance.author = self.request.user #присваиваем этой функцией текущего автора создаваемому посту
        return super().form_valid(form)


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['body', ]
    template_name = 'new_comment.html' #<app>/<model>_<view_type>.html это шаблон по которому джанго будет отрисовывать наши посты
    context_object_name = 'comments'
    # #даем запрос в БД на отображение постов в порядке добавления
    #paginate_by = 5

    def form_valid(self, form):
        form.instance.comment_author = self.request.user #присвоили коменту текущего пользователя
        form.instance.post_id = self.kwargs['pk'] #присвоили коменту айди текущего поста
        return super().form_valid(form)
  

   
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'animaltype', 'animalstatus', 'description', 'animal_image']
    template_name = 'blog/post_update.html'

    def form_valid(self, form):
        form.instance.author = self.request.user #присваиваем этой функцией текущего автора создаваемому посту
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False #функция которая позволяет редактировать только те посты, автором которых является пользователь


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получил контекст из родительского класса
        context['comments'] = Comment.objects.filter(post=self.object).order_by('-date_added')#добавил комментарии в контекст
        context['title'] = 'Post detail'
        context['variable'] = randint(1, 9)
        return context

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
        

class About(ListView):
    model = Post
    template_name = 'about.html' #<app>/<model>_<view_type>.html это шаблон по которому джанго будет отрисовывать наши посты

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получаю контекст из родительского класса
        context['post'] = Post.objects.last()
        context['posts_quantity'] = Post.objects.count()
        context['users_quantity'] = User.objects.filter(is_active=True).count()
        context['products_quantity'] = Products.objects.count()
        context['product'] = Products.objects.last()
        context['title'] = 'Animal Home'
        return context

blog/templates/about.html
{% extends "base.html" %} {% load static %} {% block content %}
<main class="wrapper">
  <h1 class="welcome workSans-h4-h3-h1">Welcome to Animalshare</h1>
  <!--? раздел херо -->
  <div class="hero">
    <div class="hero__description">
      <p class="hero__text--color workSans-h5">
        If you have seen a homeless animal or lost your pet, visit our forum and leave your ad,
        this will help find a new home for our smaller brothers.
        In the market section, you can choose products for your pet.
      </p>
      <p class="workSans-base">
        This is a test but fully working project, to demonstrate skills in working with Django and the visual part.
        The user database is stored for 24 hours. If you decide to become a sponsor, full launch is possible. 
      </p>
      <div class="hero__statistics">
        <div class="hero__post-statistics">
          <p class="spaceMono-h5-h4">{{ posts_quantity|default:'N/A' }}+</p>
          <p class="workSans-base-body">Posts</p>
        </div>
        <div class="hero__profile-statistics">
          <p class="spaceMono-h5-h4">{{ users_quantity|default:'N/A' }}+</p>
          <p class="workSans-base-body">Profiles</p>
        </div>
        <div class="hero__goods-statistics">
          <p class="spaceMono-h5-h4">{{ products_quantity|default:'N/A' }}+</p>
          <p class="workSans-base-body">Products</p>
        </div>
      </div>
    </div>
    <div class="homepage-post-cards">
      <div class="homepage-post-card">
        <a class="homepage-post-card__a" href="{{ post.animal_image.url }}">
          <img
            class="homepage-post-card__img"
            src="{{ post.animal_image.url }}"
            alt="Post picture"
        /></a>
        <div class="homepage-post-card__description">
          <a
            href="{% url 'post-detail' post.id %}"
            class="homepage-post-card__sign workSans-h5"
            >{{ post.title }}</a
          >
          <a
            href="{% url 'user-posts' post.author.username %}"
            class="homepage-post-card__author workSans-base"
          >
            <img
              class="homepage-post-card__avatar"
              src="{{ post.author.profile.image.url }}"
              alt="Avatar"
            />{{post.author}}</a
          >
        </div>
      </div>

      <div class="homepage-post-card">
        <a href="{% url 'product' product.slug %}" class="homepage-post-card__a">
          <img class="homepage-post-card__img" src="{{ product.image.url }}" alt="Post picture" />
        </a>
        <div class="homepage-post-card__description">
          <a
            href="{% url 'product' product.slug %}"
            title="{{ product.name }}"
            class="homepage-post-card__sign workSans-h5"
            >{{ product.name|truncatechars:25 }}</a
          >
          <a href="/" class="homepage-post-card__author workSans-base"
            >{{ product.sell_price }} UAH</a
          >
        </div>
      </div>
    </div>
  </div>
</main>
<!--? Конец раздела херо -->
{% endblock content %}

blog/templates/gallery.html
{% extends "base.html" %} <!-- загрузка повторяемых элементов из родительсткого шаблона -->
{% load static %}  <!-- подгружать статики нужно на каждой странице независимо есть ли эта команда в родительском шаблоне -->
{% block content %} <!-- начало уникального контента для данной страницы-->
<!--? Вставить переменную для смены bg-img -->
<section class="title bg{{variable}}">
  <!--! Вставить переменную для смены bg-img -->
  <a class="title__text wrapper workSans-h4-h3-h2" href="{% url 'forum' %}"
    >Forum</a>
</section>
<main>
  <nav class="sort__nav wrapper">
    <a class="workSans-btns-h5" href="{% url 'post-create' %}">Create a post</a>
    <a class="workSans-btns-h5" href="{% url 'user-posts' request.user.username %}">My posts</a>
    <a class="workSans-btns-h5" href="{% url 'user-comments' %}">My comments</a>
    <a class="workSans-btns-h5" href="{% url 'usertouser:inbox' %}">My messages</a>
    <a class="workSans-btns-h5 violet" href="{% url 'gallery' %}">Gallery</a>
  </nav>
  <section class="pictures">
    <div class="forum-cards--bg">
      <div class="sub-title__border">
        <h2 class="sub-title workSans-h5-h4 wrapper">Gallery</h2>
      </div>
      <div class="sub-title__border sub-title__border--in-gallery">
        <div class="pictures-cont wrapper">
        {% for post in gallery %} <!-- начало цикла словарей из модуля views.py  -->
          <div class="picture-card">
            <a class="picture-card__a-whith-img" href="{{ post.animal_image.url }}">
              <img class="picture-card__img" src="{{ post.animal_image.url }}"
                alt="Post animal">
            </a>
            <a class="picture-card__text workSans-h5" href="{% url 'post-detail' post.id %}"
            title="Go to post"
              >{{ post.title }}</a
            >
          </div>
          {% endfor %}
          {% include "blog/pagination_include.html" %}
        </div>
      </div>
<!--? Конец раздела Меин -->

{% endblock content %} <!-- конец уникального контента для данной страницы -->

blog/templates/home.html
{% extends "base.html" %}
<!-- загрузка повторяемых элементов из родительсткого шаблона -->
{% load static %}
<!-- подгружать статики нужно на каждой странице независимо есть ли эта команда в родительском шаблоне -->
{% block content %}
<!-- начало уникального контента для данной страницы-->
<section class="title bg{{variable}}">
  <!--! Вставить переменную для смены bg-img -->
  <a class="title__text wrapper workSans-h4-h3-h2" href="{% url 'forum' %}"
    >Forum</a
  >
</section>
<main>
  <nav class="sort__nav wrapper">
    <a class="workSans-btns-h5" href="{% url 'post-create' %}">Create a post</a>
    <a
      class="workSans-btns-h5"
<<<<<<< HEAD
      href="{% if user.is_authenticated %}{% url 'user-posts' request.user.username %}{% else %}{% url 'login' %}{% endif %}"
=======
    href="{% if user.is_authenticated %}{% url 'user-posts' request.user.username %}{% else %}{% url 'login' %}{% endif %}"
>>>>>>> origin/frontend
      >My posts</a
    >
    <a class="workSans-btns-h5" href="{% if user.is_authenticated %}{% url 'user-comments' %}{% else %}{% url 'login' %}{% endif %}">My comments</a>
    <a class="workSans-btns-h5" href="{% url 'usertouser:inbox' %}"
      >My messages {% if unread_messages_count %}<!--добавляем изменение на странице, если есть не прочитанные сообщения-->
      <span class="badge">{{ unread_messages_count }}</span>
      {% endif %}</a
    >
    <a class="workSans-btns-h5" href="{% url 'gallery' %}">Gallery</a>
  </nav>
  <div class="forum-cards--bg">
    <section class="forum-cards wrapper">
      <div class="post-cards-cont">
        {% for post in posts %}
        <div class="post-card clearfix">
          <a class="post-card__a" href="{{ post.animal_image.url }}"
            ><img
              class="post-card__img"
              src="{{ post.animal_image.url }}"
              alt="Post Card image"
          /></a>
          <div class="post-card__author">
            <a
              class="post-card__avatar-a workSans-h4-h3"
              href="{% url 'user-posts' post.author.username %}"
            >
              <img
                class="post-card__avatar-img"
                src="{{ post.author.profile.image.url }}"
                alt="Avatar"
            /></a>
            <div class="post-card__author-inf">
              <a
                class="post-card__author-name workSans-h4-h3"
                href="{% url 'user-posts' post.author.username %}"
                title="User posts"
                >{{post.author}}</a
              >
              <a
                class="post-card__mess workSans-btns-h5 a-as-btn btn--Outlined btn--Tertiary"
                href="{% url 'usertouser:create_message' recipient=post.author.username %}"
                title="sms"
                >Message me</a
              >
            </div>
          </div>
          <div class="post-card__post-inf">
            <a
              class="workSans-h4-h3"
              href="{% url 'post-detail' post.id %}"
              title="Comments"
              >{{ post.title }}</a
            >
            <p class="workSans-h5 violet">
              {{post.animaltype}} is {{post.animalstatus}} in
              {{post.date_posted|date:"d F - Y (H:i)"}}
            </p>
          </div>
          <p class="post-card__post-text workSans-h5">{{ post.description}}</p>
        </div>
        {% endfor %} {% include "blog/pagination_include.html" %}
      </div>
    </section>
  </div>
</main>
  {% endblock content %}
<!-- конец уникального контента для данной страницы -->

blog/templates/new_comment.html
{% extends "base.html" %}
{% load static %}
{% block title %} Add a message {% endblock %}
{% block content %}


<section class="create-smt">
<div class="wrapper">
<form class="create-smt-form" method="POST" enctype="multipart/form-data">
{% csrf_token %}
    <h2 class="create-smt__title workSans-h4-h3">New comment</h2>
        <div class="create-smt-form__input-cont create-smt-form__input-cont--column"
            >
              <textarea
                class="textarea workSans-base"
                name="body"
                cols="40"
                rows="10"
                id="id_body"
              ></textarea>
            </div>
            <button
              class="btn btn--form btn--Filled btn--Tertiary btn--margin-top20 workSans-btns"
              type="submit"
            >
              Send comment
            </button>
          </form>
        </div>
      </section>
{% endblock content %}

blog/templates/user_comments.html
{% extends "base.html" %}
<!-- загрузка повторяемых элементов из родительсткого шаблона -->
{% load static %}
<!-- подгружать статики нужно на каждой странице независимо есть ли эта команда в родительском шаблоне -->
{% block content %}
<!-- начало уникального контента для данной страницы-->
<main>
  <div class="forum-cards--bg">
    <div class="sub-title__border">
      <h2 class="sub-title workSans-btns-h5 wrapper">
        Your comments: ({{ page_obj.paginator.count }})
      </h2>
    </div>
    <section class="forum-comments">
      <div class="forum-comments-cont wrapper">
        {% for comment in comments %}
        <div class="comment-card">
          <a
            class="comment-card__avatar-a"
            href="{% url 'user-posts' comment.comment_author %}"
          >
            <img
              class="comment-card__avatar-img"
              src="{{ comment.comment_author.profile.image.url }}"
              alt="Avatar"
          /></a>
          <div class="comment-card__card-inf clearfix">
            <div class="workSans-h5-h4">
              <a
                class="violet workSans-h5-h4"
                href="{% url 'user-posts' comment.comment_author %}"
                title="My posts"
                >{{ comment.comment_author }}'s</a
              ><span> comment at
                {{comment.date_added|date:"d F - Y (H:i)" }}</span>
              in Post:<a
                class="violet workSans-h5-h4"
                href="{% url 'post-detail' comment.post.id %}"
                title="Source post"
              >
                {{ comment.post.title }}</a
              >
              <p class="workSans-h5-h4">{{ comment.body }}</p>
            </div>
            <form
              action="{% url 'delete-comment' comment.id %}"
              method="post"
              style="display: inline"
            >
              <!--начало формы и кнопки для удаления комментов-->
              {% csrf_token %}
              <button
                class="btn-delete btn--with-img btn-delete--comments"
                type="submit"
                onclick="return confirm('Are you sure you want to delete this comment?');"
              ></button>
            </form>
          </div>
        </div>
        {% endfor %} {% include "blog/pagination_include.html" %}
      </div>
    </section>
  </div>
</main>
{% endblock content %}
<!-- конец уникального контента для данной страницы -->

blog/templates/user_posts.html
{% extends "base.html" %} <!-- загрузка повторяемых элементов из родительсткого шаблона -->
{% load static %}  <!-- подгружать статики нужно на каждой странице независимо есть ли эта команда в родительском шаблоне -->
{% block content %} <!-- начало уникального контента для данной страницы-->
<main>
<div class="forum-cards--bg">
    <div class="sub-title__border">
        <h2 class="sub-title workSans-btns-h5 wrapper">
        Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})
        </h2>
    </div>
    <section class="forum-cards wrapper">
        <div class="post-cards-cont">
    {% for post in posts %}
    <div class="post-card clearfix">
      <a class="post-card__a" href="{{ post.animal_image.url }}"
        ><img
          class="post-card__img"
          src="{{ post.animal_image.url }}"
          alt="Post Card image"
      /></a>
      <div class="post-card__author">
        <a class="post-card__avatar-a workSans-h4-h3" href="{% url 'user-posts' post.author.username %}">
          <img
            class="post-card__avatar-img"
            src="{{ post.author.profile.image.url }}"
            alt="Avatar"
        /></a>
        <div class="post-card__author-inf">
          <a class="post-card__author-name workSans-h4-h3" href="{% url 'user-posts' post.author.username %}"
          title="User posts"
            >{{post.author}}</a
          >
          <a
            class="post-card__mess workSans-btns-h5 a-as-btn btn--Outlined btn--Tertiary"
            href="{% url 'usertouser:create_message' recipient=post.author.username %}"
            title="sms"
            >Message me</a
          >
        </div>
      </div>
      <div class="post-card__post-inf">
        <a class="workSans-h4-h3" href="{% url 'post-detail' post.id %}" title="Comments"
          >{{ post.title }}</a
        >
        <p class="workSans-h5 violet">
          {{post.animaltype}} is {{post.animalstatus}} in {{post.date_posted|date:"d F - Y (H:i)"}}
        </p>
      </div>
      <p class="post-card__post-text workSans-h5">
        {{ post.description}}
      </p>
    </div>
    {% endfor %}
</div>
{% include "blog/pagination_include.html" %}
</main>
{% endblock content %} <!-- конец уникального контента для данной страницы -->