animalshare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), #в аргументе (в скобках),мы указываем где искать наш шаблон, в этом примере папка users, файл login
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
   
    path('', include('blog.urls'), name='blog-home'),
    path('messages/', include('usertouser.urls', namespace='usertouser')), #тут мы реализовали пространство имен, что б не было конфликтов с хтмл файлами назанными одинаково, при указании ссылок надо добавлять префикс указанный в пространстве имен, см фалйы хтмл в usertouser
    path('shop/', include('goods.urls'), name='shop'),
    path('cart/', include('carts.urls'), name='cart'),
    path('orders/', include('orders.urls'), name='orders'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from .views import PostDetailView, PostCreateView, PostListView, PostUpdateView, PostDeleteView, UserPostListView, AddCommentView, UserCommentListView, GalleryListView, Delete_Comment, About
from . import views


urlpatterns = [
    path('forum/', PostListView.as_view(), name='forum'),#blog-home
    re_path(r'^user/(?P<username>\w{0,50})/$', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comments', AddCommentView.as_view(), name='add_comment'),
    path('post/user_comments', UserCommentListView.as_view(), name='user-comments'),
    path('comment/delete/<int:comment_id>/', Delete_Comment, name='delete-comment'),
    path('post/gallery', GalleryListView.as_view(), name='gallery'),
    path('', About.as_view(), name='home'),#blog-about
] 

orders/urls.py
from django.urls import path
from orders import views


urlpatterns = [
    path('create_order/', views.create_order, name='create-order'),
]

orders/models.py
from django.db import models
from goods.models import Products
from django.contrib.auth.models import User


class OrderitemQueryset(models.QuerySet):#аналогичная функция есть и в Carts, однако этот класс относится конкретно к высчитыванию цены именно в заказах
    
    def total_price(self):
        return sum(cart.products_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0



class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="User", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    phone_number = models.CharField(max_length=10, verbose_name="Phone number")
    requires_delivery = models.BooleanField(default=False, verbose_name="Delivery required")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Delivery adress")
    payment_on_get = models.BooleanField(default=False, verbose_name="On delivery paymant")
    is_paid = models.BooleanField(default=False, verbose_name="Paid")
    status = models.CharField(max_length=50, default='In progress', verbose_name="Order status")

    class Meta:
        db_table = "order"
        ordering = ("id",)

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}"
    
    def total_sum(self):
        return sum(item.products_price() for item in self.orderitem_set.all())#высчитываем общую стоимость заказа


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Order")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Product", default=None)
    name = models.CharField(max_length=150, verbose_name="Product name")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Price")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Quantity")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Sold date")


    class Meta:
        db_table = "order_item"
        ordering = ("id",)

    objects = OrderitemQueryset.as_manager()

    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

orders/forms.py
import re
from django import forms

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField(max_length=10)
    requires_delivery = forms.ChoiceField(choices=[("0", False),("1", True),], )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=[("0", 'False'),("1", 'True'),], )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Should be numbers only")
    
        pattern = re.compile(r'^\d{10}$')#регулярные выражения, их шаблоны можно найти в инете, форматы заполнения форм
        if not pattern.match(data):
            raise forms.ValidationError("Wrong phone number input format")

        return data

orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.core.exceptions import ValidationError
from carts.models import Carts

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem

from django.contrib.auth.models import User
from usertouser.models import usertouser

# from django.core.mail import send_mail
# from django.conf import settings

@login_required
def create_order(request):
    if request.method == 'POST':#если пост запрос, мы создаем форму при условии ее валидности
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():#атомарные транзакции - при одном запросе, выполняют множество действий и запросов с БД
                    user = request.user#команда одна - действий много, уменьшение количества товара, создание новой таблицы с записями и тд
                    cart_items = Carts.objects.filter(user=user)#получаю все корзины текущего пользователя

                    if cart_items.exists():#если все запросы и изменения произойдут без ошибок, коммит произойдет в бд, если что то из перечисленного ниже не пройдет валидацию, коммита не будет и нагрузки на бд тоже
                        # Создать заказ
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )#
                        # Создать заказанные товары
                        for cart_item in cart_items:
                            product=cart_item.product
                            if not product:
                                raise ValidationError(f'Product not found in cart item {cart_item.id}')
                            name=cart_item.product.name
                            price=cart_item.product.sell_price()
                            quantity=cart_item.quantity


                            if product.quantity < quantity:
                                raise ValidationError(f'Not enoth {name} in facility\
                                                       Aviable {product.quantity} pieces')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()#одна из транзакций, изменение количества товара в наличии

                        # Очистить корзину пользователя после создания заказа
                        cart_items.delete()
                        # Уведомление администратора через usertouser
                        admin_user = User.objects.filter(is_superuser=True).first()
                        if admin_user:
                            usertouser.objects.create(
                                sender=user,
                                recipient=admin_user,
                                subject='New Order',
                                content=f'A new order #{order.id} has been created by {user.username}.',
                            )
                        # Уведомление администратора по почте
                        # admin_user = User.objects.filter(is_superuser=True).first()
                        # if admin_user:
                        #     subject = 'New Order Notification'
                        #     message = f'A new order #{order.id} has been created by {user.username}.'
                        #     send_mail(
                        #         subject,
                        #         message,
                        #         settings.EMAIL_HOST_USER,
                        #         [admin_user.email],
                        #         fail_silently=False,
                        #     )


                        messages.success(request, 'Ordered!')
                        return redirect('profile')
            except ValidationError as e:#если трай не срабатывает, включается это условие
                messages.error(request, str(e))
                return redirect('create_order')
    else:#до пост запроса, подставляем существующие данные в форму 
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'phone_number': request.user.profile.phone_number if hasattr(request.user, 'profile') else '',  # Проверка наличия профиля
        }

        form = CreateOrderForm(initial=initial)



        form = CreateOrderForm(initial=initial)

    context = {
        'form': form,
        'order': True,
        'title':'Order creation',
    }
    return render(request, 'orders/create_order.html', context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main class="create-order">
    <div class="wrapper">
        {% include "carts/includes/included_cart.html" %} <!--заинклудил разметку корзины, дальше пишем форму доставки и оплаты-->
    </div>
    <div class="forum-cards--bg">
        <div class="wrapper">
            <h2 class="profile-top__title profile-top__title--under profile-top__title--834-left workSans-h4-h3">Order details</h2>
            <div class="#">
                <div class="profile-top-cont">
                    <div class="profile-top__details">
                        <form class="change-profile-form" action="{% url 'create-order' %}"
                        method="post"
                        id="create_order_form"
                        enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="create-smt-form">
                                <div class="create-smt-form__input-cont">
                                    <label for="id_first_name" class="workSans-base-body">*First name:</label>
                                    <input type="text"
                                    class="form-input create-acc-form__input--username workSans-base"
                                    id="id_first_name"
                                        value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                        name="first_name" required>
                                    {% if form.first_name.errors %}
                                        <div class="">{{form.first_name.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="create-smt-form__input-cont">
                                    <label for="id_last_name" class="workSans-base-body">*Last name:</label>
                                    <input type="text"
                                    class="form-input create-acc-form__input--username workSans-base"
                                    id="id_last_name" name="last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                    required>
                                    {% if form.last_name.errors %}
                                        <div class="">{{form.last_name.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="create-smt-form__input-cont">
                                    <label for="id_phone_number" class="workSans-base-body">*Phone number:</label>
                                    <input type="text"
                                    class="form-input create-acc-form__input--phone workSans-base"
                                    id="id_phone_number" name="phone_number"
                                        value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                        placeholder="(000) 000-00-00"
                                        required>
                                    {% if form.phone_number.errors %}
                                        <div class="">{{form.phone_number.errors}}</div>
                                    {% endif %}
                                    <div class="" style="display: none" id="phone_number_error">Wrong number added.</div>
                                </div>
                                <div class="create-smt-form__input-cont" id="deliveryAddressField">
                                    <label for="id_delivery_address" class="workSans-base-body">*Delivery adress:</label>
                                    <textarea class="form-input form-input--without-img workSans-base" id="id_delivery_address"
                                        value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}"
                                        name="delivery_address" rows="2" placeholder="Skip if not neccesarry"></textarea>
                                    {% if form.delivery_address.errors %}
                                        <div class="">{{form.delivery_address.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="create-smt-form__input-cont">
                                    <label for="delivery" class="workSans-base-body">Delivery type: </label>
                                    <div class="create-smt-form__input-cont--column">
                                        <div class="#">
                                            <input class="sort__dropdown-menu-switch" type="radio" name="requires_delivery"
                                                id="id_requires_delivery" value="1" checked>
                                            <label class="workSans-base-body" for="id_requires_delivery">Bring it to me</label>
                                        </div>
                                        <div class="#">
                                            <input class="sort__dropdown-menu-switch" type="radio" name="requires_delivery"
                                                id="id_requires_delivery" value="0">
                                            <label class="workSans-base-body" for="id_requires_delivery">I'll carry it by myself</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="create-smt-form__input-cont">
                                    <label class="workSans-base-body">Payment method: </label>
                                    <div class="create-smt-form__input-cont--column">
                                        <div class="#">                                        
                                            <input class="sort__dropdown-menu-switch" type="radio" name="payment_on_get"
                                                id="id_payment_on_get" value="0" checked>
                                            <label class="workSans-base-body" for="id_payment_on_get">Credit card</label>
                                        </div>
                                        <div class="#">
                                            <input class="sort__dropdown-menu-switch" type="radio" name="payment_on_get"
                                                id="id_payment_on_get" value="1">
                                            <label class="workSans-base-body" for="id_payment_on_get">By cash when delivered</label>
                                            {% if form.payment_on_get.errors %}
                                                <div class="">{{form.payment_on_get.errors}}</div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn--form btn--Filled btn--Tertiary btn--margin-top20 workSans-btns">I need it!</button><br><br>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}