animalshare/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'), #в аргументе (в скобках),мы указываем где искать наш шаблон, в этом примере папка users, файл login
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
   
    path('', include('blog.urls'), name='blog-home'),
    path('messages/', include('usertouser.urls', namespace='usertouser')), #тут мы реализовали пространство имен, что б не было конфликтов с хтмл файлами назанными одинаково, при указании ссылок надо добавлять префикс указанный в пространстве имен, см фалйы хтмл в usertouser
    path('shop/', include('goods.urls'), name='shop'),
    path('cart/', include('carts.urls'), name='cart'),
    path('orders/', include('orders.urls'), name='orders'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from .views import PostDetailView, PostCreateView, PostListView, PostUpdateView, PostDeleteView, UserPostListView, AddCommentView, UserCommentListView, GalleryListView, Delete_Comment, About
from . import views


urlpatterns = [
    path('forum/', PostListView.as_view(), name='forum'),#blog-home
    re_path(r'^user/(?P<username>\w{0,50})/$', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comments', AddCommentView.as_view(), name='add_comment'),
    path('post/user_comments', UserCommentListView.as_view(), name='user-comments'),
    path('comment/delete/<int:comment_id>/', Delete_Comment, name='delete-comment'),
    path('post/gallery', GalleryListView.as_view(), name='gallery'),
    path('', About.as_view(), name='home'),#blog-about
] 

usertouser/urls.py
from django.urls import path
from .views import usertouserCreateView, usertouserListView, usertouserDetailListView, usertouserOutboxListView
app_name = 'usertouser' #указание для пространства имен в главном файле url.py


urlpatterns = [
path('sms/inbox/', usertouserListView.as_view(template_name='messages/inbox.html'), name='inbox'),
path('sms/create/<str:recipient>/', usertouserCreateView.as_view(), name='create_message'),
path('sms/outbox/', usertouserOutboxListView.as_view(template_name='messages/outbox.html'), name='outbox'),
path('sms/<int:pk>/', usertouserDetailListView.as_view(), name='detail'), 
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    animaltype = models.CharField(max_length=50)
    animalstatus = models.CharField(max_length=50, null=True)
    description = models.TextField()
    animal_image = models.ImageField(default='default_animal.jpg', upload_to='animal_pics')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
   

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk}) #перенаправление после создания поста в детали поста
    
    def __str__(self) -> str:
        return self.title
    

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE, null = True)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'Author {self.comment_author}| post title {self.post.title}'
    #   return '%s - %s' % (self.post.title, self.comment_author)
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.post.pk})

blog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Post, Comment
from goods.models import Products
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from random import randint



class PostListView(ListView):
    model = Post
    template_name = 'home.html' #<app>/<model>_<view_type>.html это шаблон по которому джанго будет отрисовывать наши посты
    context_object_name = 'posts' #показываем название что зацикливать
    ordering = ['-date_posted'] #даем запрос в БД на отображение постов в порядке добавления
    paginate_by = 5 # метод, который позволяет оставить 5 постов на одну страницу

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получаю контекст из родительского класса
        context['comments'] = Comment.objects.all().order_by('-date_added')
        context['posts_quantity'] = Post.objects.count()
        context['users_quantity'] = User.objects.filter(is_active=True).count()
        context['products_quantity'] = Products.objects.count()
        context['title'] = 'Forum'
        context['variable'] = randint(1, 9)
        return context


class UserPostListView(ListView): #создание класса который отфильтрует посты пользователя
    model = Post
    template_name = 'user_posts.html' 
    context_object_name = 'posts'
    paginate_by = 5
    ordering = ['-date_posted']

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class GalleryListView(ListView): #создание класса который отфильтрует из БД все картинки
    model = Post
    template_name = 'gallery.html' 
    context_object_name = 'gallery'
    paginate_by = 18
    ordering = ['?']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получаю контекст из родительского класса
        context['gallery'] = Post.objects.exclude(animal_image='default_animal.jpg')#реализовано условие выборки из БД, КРОМЕ (что б не отображались стандартные пикчи животных)
        context['variable'] = randint(1, 9)
        context['title'] = 'Gallery'
        return context
    

class UserCommentListView(ListView): #создание класса который отфильтрует комментарии пользователя
    model = Comment
    template_name = 'user_comments.html' 
    context_object_name = 'comments'
    paginate_by = 20
    ordering = ['-date_added']

    def get_queryset(self):
        user = get_object_or_404(User, id=self.request.user.id)
        return Comment.objects.filter(comment_author=user).select_related('comment_author')

@login_required
def Delete_Comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, comment_author=request.user)
    if request.method == 'POST':
        comment.delete()
        return redirect('user-comments')  # Перенаправление на страницу с комментариями
    return render(request, 'confirm_delete.html', {'comment': comment}, {'title': 'Your comments'},)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'animaltype', 'animalstatus', 'description', 'animal_image']

    def form_valid(self, form):
        form.instance.author = self.request.user #присваиваем этой функцией текущего автора создаваемому посту
        return super().form_valid(form)


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['body', ]
    template_name = 'new_comment.html' #<app>/<model>_<view_type>.html это шаблон по которому джанго будет отрисовывать наши посты
    context_object_name = 'comments'
    # #даем запрос в БД на отображение постов в порядке добавления
    #paginate_by = 5

    def form_valid(self, form):
        form.instance.comment_author = self.request.user #присвоили коменту текущего пользователя
        form.instance.post_id = self.kwargs['pk'] #присвоили коменту айди текущего поста
        return super().form_valid(form)
  

   
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'animaltype', 'animalstatus', 'description', 'animal_image']
    template_name = 'blog/post_update.html'

    def form_valid(self, form):
        form.instance.author = self.request.user #присваиваем этой функцией текущего автора создаваемому посту
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False #функция которая позволяет редактировать только те посты, автором которых является пользователь


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получил контекст из родительского класса
        context['comments'] = Comment.objects.filter(post=self.object).order_by('-date_added')#добавил комментарии в контекст
        context['title'] = 'Post detail'
        context['variable'] = randint(1, 9)
        return context

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
        

class About(ListView):
    model = Post
    template_name = 'about.html' #<app>/<model>_<view_type>.html это шаблон по которому джанго будет отрисовывать наши посты

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)#получаю контекст из родительского класса
        context['post'] = Post.objects.last()
        context['posts_quantity'] = Post.objects.count()
        context['users_quantity'] = User.objects.filter(is_active=True).count()
        context['products_quantity'] = Products.objects.count()
        context['product'] = Products.objects.last()
        context['title'] = 'Animal Home'
        return context

blog/templates/blog/pagination_include.html
<div class="pagination workSans-btns-h5">
    <div class="pagination-numbers">
    {% if is_paginated %} <!--начало логики для пагинации-->
      {% if page_obj.has_previous %}
      <P class="pagination-numbers"><a href="?page=1">First page</a></P>
      <a class="pagination-arrow--left" href="?page={{ page_obj.previous }}"></a>
      {% endif %}
    
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <P class="pagination-numbers"><a href="?page={{ num }}">{{ num }}</a></P>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <P class="pagination-numbers"><a href="?page={{ num }}">{{ num }}</a></P>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
      <a class="pagination-arrow--right" href="?page={{ page_obj.next_page_number }}"></a>
      <P class="pagination-numbers"><a href="?page={{ page_obj.paginator.num_pages }}">Last page</a></P>
      {% endif %}
    {% endif %}
    </div>
</div>

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<center><form method="POST">
    {% csrf_token %}
    <h1 class="create-acc__title workSans-h3-h2">Delete Post</h1>
    <p class="workSans-base-body">Are you sure you wont to delete Post "{{ object.title }}"</p>
    <button
    class="btn btn--form btn--Filled btn--Tertiary btn--margin-top20 workSans-btns"
    type="submit">
    Yes, delete!
  </button><br><br>
  <a
  href="{% url 'post-detail' object.id %}"
  class="a-as-btn btn btn--form btn--Outlined btn--Tertiary workSans-btns"
  >Cancel</a>
</form></center>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "base.html" %} <!-- загрузка повторяемых элементов из родительсткого шаблона -->
{% load static %}  <!-- подгружать статики нужно на каждой странице независимо есть ли эта команда в родительском шаблоне -->
{% block content %} <!-- начало уникального контента для данной страницы-->
<section class="title bg{{variable}}">
    <!--! Вставить переменную для смены bg-img -->
    <a class="title__text wrapper workSans-h4-h3-h2" href="{% url 'forum' %}"
      >Forum</a
    >
  </section>
  <main>
    <nav class="sort__nav wrapper">
      <a class="workSans-btns-h5" href="{% url 'post-create' %}">Create a post</a>
      <a class="workSans-btns-h5" href="{% url 'user-posts' request.user.username %}">My posts</a>
      <a class="workSans-btns-h5" href="{% url 'user-comments' %}">My comments</a>
      <a class="workSans-btns-h5" href="{% url 'usertouser:inbox' %}">My messages
        {% if unread_messages_count %}<!--добавляем изменение на странице, если есть не прочитанные сообщения-->
          <span class="badge">{{ unread_messages_count }}</span>
        {% endif %}</a>
      <a class="workSans-btns-h5" href="{% url 'gallery' %}">Gallery</a>
    </nav>
<div class="forum-cards--bg">
    <section class="forum-cards wrapper">
      <div class="post-cards-cont">
        <div class="post-card clearfix">
          <a class="post-card__a" href="{{ post.animal_image.url }}"
            ><img
              class="post-card__img"
              src="{{ post.animal_image.url }}"
              alt="Post Card image"
          /></a>
          <div class="post-card__author">
            <a class="post-card__avatar-a workSans-h4-h3" href="{% url 'user-posts' post.author.username %}">
              <img
                class="post-card__avatar-img"
                src="{{ post.author.profile.image.url }}"
                alt="Avatar"
            /></a>
            <div class="post-card__author-inf">
              <a class="post-card__author-name workSans-h4-h3" href="{% url 'user-posts' post.author.username %}"
              title="User posts"
                >{{post.author}}</a
              >
              <a
                class="post-card__mess workSans-btns-h5 a-as-btn btn--Outlined btn--Tertiary"
                href="{% url 'usertouser:create_message' recipient=post.author.username %}"
                title="sms"
                >Message me</a
              >
            </div>
          </div>
          <div class="post-card__post-inf">
            <p class="workSans-h4-h3" href="{% url 'post-detail' post.id %}" title="Comments"
              >{{ post.title }}</p
            >
            <p class="workSans-h5 violet">
              {{post.animaltype}} is {{post.animalstatus}} in {{post.date_posted|date:"d F - Y (H:i)"}}
            </p>
          </div>
          <p class="post-card__post-text workSans-h5">
            {{ post.description}}
          </p>
        </div>
<section class="forum-comments">
    <div class="sub-title-cont__border">
        <div class="sub-title-cont wrapper">
        <h2 class="violet workSans-btns-h5">Comments</h2>
{% if user.is_authenticated %}
<a class="workSans-btns-h5" href="{% url 'add_comment' post.pk %}"
>Add a comment</a></div>
{% else %}
<a class="workSans-btns-h5" href="{% url 'add_comment' post.pk %}"
>Log in to be able to add comments</a></div>
{% endif %}
{% if not comments %}
<div class="sub-title-cont wrapper">
<h3 class="workSans-btns-h5">No comments yet! Be the first one!</h3></div>
{% else %}
<div class="forum-comments-cont wrapper"></div>
{% for comment in comments %}
<div class="comment-card">
    <a class="comment-card__avatar-a" href="{% url 'user-posts' comment.comment_author %}">
      <img
        class="comment-card__avatar-img"
        src="{{ comment.comment_author.profile.image.url }}"
        alt="Avatar"
    /></a>

    <div class="comment-card__card-inf clearfix">
      <p class="workSans-h5 violet">
        <a class="workSans-h5-h4" href="{% url 'user-posts' comment.comment_author %}">{{ comment.comment_author }}'s comment at
        {{ comment.date_added|date:"d F - Y (H:i)" }}</a>
        <p class="workSans-h5-h4">{{ comment.body }}</p>
      </p>
    </div>
  </div>
    {% endfor %}
{% endif %}
{% include 'blog/pagination_include.html' %}
{% if object.author == user %}
<a href="{% url 'post-update' post.id %}"
    class="a-as-btn btn btn--form btn--Outlined btn--Tertiary workSans-btns"
    >Update Post</a>
<a href="{% url 'post-delete' post.id %}"
    class="a-as-btn btn btn--form btn--Outlined btn--Tertiary workSans-btns"
    >Delete Post</a>
{% endif %}
{% endblock content %} <!-- конец уникального контента для данной страницы -->

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p><b>New Post</b></p>
    {{ form.as_p }} <!-- вставляет стандартную форму из Джанго, а команда .as_p разбивает форму на параграфы-->
    <p>
        <button type="submit">Send Post</button>
    </p>
</form>
{% endblock content %}

blog/templates/blog/post_update.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="create-smt">
    <div class="wrapper">
<form class="create-smt-form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 class="create-smt__title workSans-h4-h3">Change some values</h2>
    <div class="create-smt-form__input-cont">
      <label class="workSans-base-body" for="id_title">Title:</label>
      <input
        class="form-input form-input--without-img workSans-base"
        maxlength="100"
        type="text"
        name="title"
        id="id_title"
        value="{% if form.title.value %}{{ form.title.value }}{% endif %}"
        required
      />
    </div>
    <div class="create-smt-form__input-cont">
      <label class="workSans-base-body" for="id_animaltype"
        >Animaltype:</label
      >
      <input
        class="form-input form-input--without-img workSans-base"
        type="text"
        name="animaltype"
        id="id_animaltype"
        value="{% if form.animaltype.value %}{{ form.animaltype.value }}{% endif %}"
        maxlength="50"
        required
      />
    </div>
    <div class="create-smt-form__input-cont">
      <label class="workSans-base-body" for="id_animalstatus"
        >Animalstatus:</label
      >
      <input
        class="form-input form-input--without-img workSans-base"
        type="text"
        name="animalstatus"
        id="id_animalstatus"
        value="{% if form.animalstatus.value %}{{ form.animalstatus.value }}{% endif %}"
        maxlength="50"
        required
      />
    </div>
    <div class="create-smt-form__input-cont">
      <p class="workSans-base-body">Animal image:</p>
      <label
        class="select-file-label btn btn--form btn--Outlined btn--Tertiary workSans-btns"
        for="id_animal_image"
        >Select file</label
      >
      <input
        class="hidden"
        type="file"
        name="animal_image"
        id="id_animal_image"
        value="{% if form.animal_image.value %}{{ form.animal_image.value }}{% endif %}"
        accept="image/*"
      />
    </div>
    {% if form.id_animal_image.value %}{{ form.id_animal_image.value }}{% endif %}

    <div
      class="create-smt-form__input-cont create-smt-form__input-cont--column"
    >
      <label class="workSans-base-body" for="id_description"
        >Description:</label
      >
      <textarea
        class="textarea workSans-base"
        name="description"
        cols="40"
        rows="10"
        id="id_description"
        value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
        required
      ></textarea>
    </div>
    <button
      class="btn btn--form btn--Filled btn--Tertiary btn--margin-top20 workSans-btns"
      type="submit"
    >
      Update Post
    </button>
  </form><br><br>
  <a href="{% url 'post-delete' post.id %}"
    class="a-as-btn btn btn--form btn--Outlined btn--Tertiary workSans-btns"
    >Delete Post</a>
  </div>
</section>
</main>
{% endblock content %}